# Vars

@baseURL = http://localhost:1337

### --------------
###  thread-sets
### --------------

### findAll
GET {{baseURL}}/api/thread-sets/4

### store
POST {{baseURL}}/api/thread-sets
Content-Type: application/json

{
    "data": {
        "name": "Python",
        "description": "The shitest lang in the world"
    }
}

### delete
DELETE {{baseURL}}/api/thread-sets/2

### ----------
###  threads
### ----------

### findAll
GET {{baseURL}}/api/threads

### findAll com populate em ThreadSet
GET {{baseURL}}/api/threads?populate=*

### findAll para todas as Threads de um ThreadSetId=?
@threadSetId=5
GET {{baseURL}}/api/threads?filters[thread_set][id][$eq]={{threadSetId}}

### store
//cThreadSetId=4
//pythonThreadSetId=5
POST {{baseURL}}/api/threads
Content-Type: application/json

{
    "data": {
        "title": "If python then eu não",
        "thread_set": 5,
        "isFixed": false
    }
}

### delete
DELETE {{baseURL}}/api/threads

###--- Login ---###
GET {{baseURL}}/api/users/me?populate=role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzI2NDg4NzQ1LCJleHAiOjE3MjkwODA3NDV9.S83DZKnZJjlfmH_6YA6lwrOXbdkHicc35SOt8AW1FZA