# Vars
@baseURL = http://localhost:1337

### findAll
GET {{baseURL}}/api/thread-sets/17
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzI2NTgyNDAzLCJleHAiOjE3MjkxNzQ0MDN9.X0mm23w3PcAwg8iktRXqgCmgH5lyIHErDRNOUxT1f4s

### store
POST {{baseURL}}/api/thread-sets
Content-Type: application/json

{
    "data": {
        "name": "Python",
        "description": "The shitest lang in the world"
    }
}

### update
PUT {{baseURL}}/api/thread-sets/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzI2NTgyNDAzLCJleHAiOjE3MjkxNzQ0MDN9.X0mm23w3PcAwg8iktRXqgCmgH5lyIHErDRNOUxT1f4s

{
    "name": "blabla"
}

### delete
DELETE {{baseURL}}/api/thread-sets/2