# Vars
@baseURL = http://localhost:1337
@nifotoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzI2NTgyNDQwLCJleHAiOjE3MjkxNzQ0NDB9.GP8m1vgGKx3FOfr8-NN5c8ZeEgSd0Yveexhvm3VaUUY
@nifoadmtoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzI2NTgyNDAzLCJleHAiOjE3MjkxNzQ0MDN9.X0mm23w3PcAwg8iktRXqgCmgH5lyIHErDRNOUxT1f4s

### Login
POST {{baseURL}}/api/auth/local
Content-Type: application/json

{
    "identifier": "nifo18@email.com",
    "password": "123456"
}

### update
PUT {{baseURL}}/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzI2NTgyNDAzLCJleHAiOjE3MjkxNzQ0MDN9.X0mm23w3PcAwg8iktRXqgCmgH5lyIHErDRNOUxT1f4s
Content-Type: application/json

{
    "image": 3
}

### Me infos
GET {{baseURL}}/api/users/me?populate=role,image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzI2NTgyNDAzLCJleHAiOjE3MjkxNzQ0MDN9.X0mm23w3PcAwg8iktRXqgCmgH5lyIHErDRNOUxT1f4s
